In [21]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree, metrics
import numpy as np

import MNISTData

In [22]:
# get data
print("Loading Data...")
mnist = MNISTData.MNISTData(data_dir="data/")

Loading Data...


In [26]:
# build boosted decision tree classifier
classifier = RandomForestClassifier(n_estimators=100)
classifier = classifier.fit(mnist.train.data, mnist.train.labels)

In [27]:
# calculate predictions on test data
print("Making Predictions...")
predicted_labels = classifier.predict(mnist.test.data)

Making Predictions...


In [28]:
# evaluate predictions
print("Evaluating Classifier...")
accuracy = metrics.accuracy_score(mnist.test.labels, predicted_labels)
confusion_matrix = metrics.confusion_matrix(mnist.test.labels, predicted_labels)

print("========Results========")
print("Accuracy: %f" % (accuracy))
print(confusion_matrix)

Evaluating Classifier...
========Results========
Accuracy: 0.962698
[[601   0   0   0   0   1   4   0   4   1]
 [  0 704   2   3   0   1   0   1   0   1]
 [  3   4 613   4   4   0   4   3   6   1]
 [  3   0  14 588   0   9   2   4  11   3]
 [  1   1   1   0 579   0   0   2   2  10]
 [  3   1   1  12   1 535   5   1   2   6]
 [  2   2   1   0   0   6 630   0   0   0]
 [  0   5   5   1   2   0   0 637   2   5]
 [  2   4   3   5   2   2   1   1 571   9]
 [  2   1   1   6  10   2   0   7   4 607]]
