In [1]:
from sklearn import svm, metrics
from sklearn.ensemble import BaggingClassifier
import numpy as np

import MNISTData

In [2]:
# get data
print("Loading Data...")
mnist = MNISTData.MNISTData(data_dir="data/")

Loading Data...


In [3]:
def evaluate_model(fitted_model):
    # calculate predictions on test data
    print("Making Predictions...")
    predicted_labels = fitted_model.predict(mnist.test.data)
    # evaluate predictions
    print("Evaluating Classifier...")
    accuracy = metrics.accuracy_score(mnist.test.labels, predicted_labels)
    confusion_matrix = metrics.confusion_matrix(mnist.test.labels, predicted_labels)

    print("========Results========")
    print("Accuracy: %f" % (accuracy))
    print(confusion_matrix)

In [ ]:
# build simple SVM classifier
num_train = 10000
simple_svm = svm.SVC(verbose=True)
simple_svm = simple_svm.fit(mnist.train.data[:num_train], mnist.train.labels[:num_train]) 
# takes forever on full dataset...

In [13]:
# build bagged SVM
options = {'base_estimator': svm.SVC(),
           'n_estimators': 16,
           'max_samples': 0.1,
           'max_features': 1.0,
           'oob_score': False,
           'n_jobs': 8,
           'verbose': 0}

bagging = BaggingClassifier(**options)

In [14]:
bagging = bagging.fit(mnist.train.data, mnist.train.labels)

In [15]:
evaluate_model(bagging)

Making Predictions...
Evaluating Classifier...
========Results========
Accuracy: 0.885238
[[582   0   4   2   1   6   7   0   7   2]
 [  0 701   1   2   0   3   0   2   2   1]
 [  8  18 529  10  14   2  19  12  28   2]
 [  2   7  24 537   2  22   6   7  18   9]
 [  1   6   5   1 531   0   4   2   1  45]
 [  5  19   4  39   7 472  12   1   3   5]
 [  8   9  11   0   2  10 599   0   2   0]
 [  1  22   9   0   9   2   0 591   2  21]
 [  4  33   9  25   5  18   3   4 485  14]
 [  4   7   3   8  34   1   1  29   3 550]]
